name: Run Ansible Playbook

on:
  push:
    branches: [prod]  # Trigger when code is merged into prod
  workflow_dispatch:  # Allow manual run if needed

jobs:
  ansible:
    name: Provision Webservers with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Ansible Playbook with Correct Python
        env:
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.yaml ansible/playbooks/install_apache.yaml



      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.yaml ansible/playbooks/install_apache.yaml
