name: Run Ansible Playbook

on:
  push:
    branches: [prod]  # Trigger when code is merged into prod
  workflow_dispatch:  # Allow manual run if needed

jobs:
  ansible:
    name: Provision Webservers with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install boto and dependencies for dynamic inventory
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install boto3 botocore


      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.yaml ansible/playbooks/install_apache.yaml
