name: Run Ansible Playbook

on:
  push:
    branches: [prod]  # Trigger when code is merged into prod
  workflow_dispatch:  # Allow manual run if needed

jobs:
  ansible:
    name: Provision Webservers with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ansible + Boto3
        run: |
          sudo apt update
          sudo apt install -y ansible python3-boto3

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.yaml ansible/playbooks/install_apache.yaml
